### ISSUE TITLE
Stackblitz demo not working with 3.12.0

### ISSUE THREAD

**Issue by ottosson** [TemainfoSoftware/truly-ui#299]
I want to reproduce a potential problem with the library using Stackblitz, but I can't get the latest version of Truly-ui to work. It says 

> Cannot find module 'truly-ui'.

**To Reproduce**
- open https://stackblitz.com/edit/truly-ui-simple
- update dependencies to latest version (3.12.0 atm).

**Comment by abalad** [comment]
@ottosson I updated the dependencies in the Stackblitz, check now please?

**Comment by abalad** [comment]
![image](https://user-images.githubusercontent.com/5459282/57625624-9e0ac580-756a-11e9-8d84-1689845b0248.png)

**Comment by abalad** [comment]
![image](https://user-images.githubusercontent.com/5459282/57625720-cf839100-756a-11e9-80fb-bd210242bc8e.png)

**Comment by ottosson** [comment]
Seems to work. Thanks!
